apiVersion: apps/v1
kind: Deployment
metadata:
  name: result
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: result
  template:
    metadata:
      labels:
        app: result
    spec:
      containers:
      - name: result
        image: rajneeshhajelaai/result:1.0.0
        ports:
        - name: http
          containerPort: 80
      # exporter removed (invalid image)
