apiVersion: v1
kind: Service
metadata:
  labels:
    app: vote
  name: vote
spec:
  type: NodePort
  ports:
  - name: "vote-service"
    port: 5000
    targetPort: 80
    nodePort: 31002
  selector:
    app: vote
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vote
  template:
    metadata:
      labels:
        app: vote
    spec:
      containers:
      - name: vote
        image: rajneeshhajelaai/vote:1.0.0
        command: ["gunicorn"]
        args:
          - "--access-logfile"
          - "-"
          - "--error-logfile"
          - "-"
          - "--workers"
          - "4"
          - "--bind"
          - "0.0.0.0:80"
          - "app:app"
        ports:
        - name: http
          containerPort: 80
      # ❌ exporter removed
